name: Update Stock Database

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write Firebase serviceAccount.json
        run: echo '${{ secrets.FIREBASE_KEY_JSON }}' > serviceAccount.json

      - name: Run test script
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        run: python test/test.py

      - name: Run update script
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        run: python update_db.py