name: Update Stock Database

on:
  schedule:
    - cron: '0 0 * * *'    
  workflow_dispatch:       

jobs:
  update:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    permissions:
      contents: write   

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        run: python update_db.py

      - name: Commit and push updated stocks.db
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add stocks.db
          git commit -m "Auto-update stocks.db [skip ci]" || echo "No changes to commit"
          git push
