name: Update Stock Database

on:
  schedule:
    - cron: '*/10 * * * *'    
  workflow_dispatch:          

jobs:
  update:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend   

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'      

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        run: python update_db.py

      - name: Upload SQLite database artifact
        uses: actions/upload-artifact@v4
        with:
          name: stocks-db
          path: backend/stocks.db
